name = "cf-svelte-ts"
account_id = ""
workers_dev = true
main = "./.svelte-kit/cloudflare/"
compatibility_date = "2023-04-19"
compatibility_flags = [ "nodejs_compat" ]

[triggers]
crons = ["*/30 * * * *"]

[site]
bucket = ".svelte-kit/output/"
